version: "3.3"
services:
  redis-1:
    image: "redis:6.0.9-alpine"
    container_name: redis-1
    command: redis-server /usr/local/etc/redis/redis.conf --bind redis-1
    volumes:
      - ./conf/redis79.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

  redis-2:
    image: "redis:6.0.9-alpine"
    container_name: redis-2
    command: redis-server /usr/local/etc/redis/redis.conf --bind redis-2
    volumes:
      - ./conf/redis80.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6380:6379

  sentinel:
    image: "redis:6.0.9-alpine"
    container_name: sentinel
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf --bind sentinel
    volumes:
      - ./conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    ports:
      - 26379:26379
